ALARM_CHECK = "alarm_check"
ALARM_NONE = "alarm_none"
ALARM_NOTE = "alarm_note"
ALARM_OFF = "alarm_off"
ALARM_PLUS = "alarm_plus"
WIFI_CONNECTED = "wifi_connected"
WIFI_DISCONNECTED = "wifi_disconnected"
WIFI_WAIT = "wifi_wait"
